plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zoro.batterywallpaper'
    compileSdk 34

    defaultConfig {
        applicationId "com.zoro.batterywallpaper"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.preference:preference:1.2.1'
}
